apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "scalesets.prescaler.kloia.com"
spec:
  group: "prescaler.kloia.com"
  versions: 
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["namespacename","deploymentname","hpaname","defaultreplicas"]
              properties:
                namespacename:
                  type: "string"
                deploymentname:
                  type: "string"
                hpaname:
                  type: "string"
                defaultreplicas:
                  type: "integer"
  scope: "Cluster"
  names:
    plural: "scalesets"
    singular: "scaleset"
    kind: "Scaleset"
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "criticalteams.prescaler.kloia.com"
spec:
  group: "prescaler.kloia.com"
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["criticalteamid"]
              properties:
                criticalteamid:
                  type: "integer"
  scope: "Cluster"
  names:
    plural: "criticalteams"
    singular: "criticalteam"
    kind: "Criticalteam"
---
apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "percents.prescaler.kloia.com"
spec:
  group: "prescaler.kloia.com"
  versions: 
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["minpercent","maxpercent","criticalminpercent","criticalmaxpercent"]
              properties:
                minpercent:
                  type: "integer"
                maxpercent:
                  type: "integer"
                criticalminpercent:
                  type: "integer"
                criticalmaxpercent:
                  type: "integer"
  scope: "Namespaced"
  names:
    plural: "percents"
    singular: "percent"
    kind: "Percent"