apiVersion: v1
kind: ServiceAccount
metadata:
  name: prescaler-sa
  namespace: prescaler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: prescaler-sa-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: prescaler-sa
  namespace: prescaler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescaler
  labels:
    app: prescaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prescaler
  template:
    metadata:
      labels:
        app: prescaler
    spec:
      containers:
      - name: kubectl
        environmenv:
        - name: wait
          value: "5m"
        image: kloiadocker/prescaler:0.1
      serviceAccountName: prescaler-sa